name: yohaura
description: A new Flutter project.

# Prevents the package from being accidentally published to pub.dev.
publish_to: 'none' 

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  image_picker: ^0.8.4+1
  exif: ^2.0.4
  path_provider: ^2.0.8
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here.
  # Each entry in this list should have a "family" key with the font family name,
  # and a "fonts" key with a list giving the asset and other descriptors for the font. 
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
